addSbtPlugin("org.scalameta"             % "sbt-scalafmt"   % "2.4.6")
addSbtPlugin("ch.epfl.scala"             % "sbt-scalafix"   % "0.9.34")
addSbtPlugin("com.github.sbt"            % "sbt-ci-release" % "1.5.10")
addSbtPlugin("com.github.sbt"            % "sbt-pgp"        % "2.1.2")
addSbtPlugin("org.scoverage"             % "sbt-scoverage"  % "1.9.3")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"   % "0.1.20")
