addSbtPlugin("org.scalameta"  % "sbt-scalafmt" % "2.4.3")
addSbtPlugin("ch.epfl.scala"  % "sbt-scalafix" % "0.9.33")
addSbtPlugin("com.github.sbt" % "sbt-release"  % "1.1.0")
addSbtPlugin("org.xerial.sbt" % "sbt-sonatype" % "3.9.10")
addSbtPlugin("com.jsuereth"   % "sbt-pgp"      % "2.0.1")
