name: CI Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    paths:
      - "**.scala"
      - "**.sbt"
      - "**.conf"
      - "**.properties"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Scala
        uses: olafurpg/setup-scala@v13
        with:
          java-version: adopt@1.8
      - name: Coursier cache
        uses: coursier/cache-action@v6
      - name: Run tests
        run: sbt ciBuild
