name: PR Builder

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
      - name: Coursier cache
        uses: coursier/cache-action@v6
      - name: Run tests
        run: sbt prBuild
